---
- hosts: all
  become: true
  gather_facts: false
  ignore_errors: true

- roles:
   - rhel8_patching

- name: send an email using Gmail SMTP Servers
  community.general.mail
      name: Sending an e-mail using Gmail SMTP servers
      host: smtp.gmail.com
      port: 587   
      username: darcy.cook35@gmail.com
      password: {{ secret }}
      to: Darcy Bank <darcybank@gmail.com>
      subject: Ansible-report
      body: System {{ ansible_hostname }} has been successfully provisioned.
  delegate_to: localhost
    ignore_errors: yes
